version: '3.4'

services:
  2024goldandsilverdashboard:
    image: kssocha2024goldandsilverdashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/visualization/visualize.py "]
    ports:
      - 5678:5678
